/**
 * This file generated by Apso.
 */
import { ArticleModule } from './Article/Article.module';
import { CategoryModule } from './Category/Category.module';
import { ArticleCategoryModule } from './ArticleCategory/ArticleCategory.module';
import { UserModule } from './User/User.module';
import { CommentModule } from './Comment/Comment.module';

export default [
  ArticleModule,
  CategoryModule,
  ArticleCategoryModule,
  UserModule,
  CommentModule,
];
